version: '3'
services:
  next-app:
    build: ./next-app
    container_name: next-app
    ports:
      - "3000:3000"
    depends_on:
      - api
    image: yutive/next-app
  api:
    build: ./api
    container_name: api
    ports:
      - "8080:8080"
    image: yutive/api
  db:
    image: mongo:6.0.4-jammy
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: cocktail
      MONGO_INITDB_ROOT_PASSWORD: cocktail
      MONGO_INITDB_DATABASE: cocktail