version: '3'
services:
  next-app:
    build: ./next-app
    container_name: next-app
    ports:
      - "3000:3000"
    depends_on:
      - api
    image: yutive/next-app
  api:
    build: ./api
    container_name: api
    ports:
      - "8080:8080"
    image: yutive/api
  db:
    image: mongo:6.0.4-jammy
    restart: on-failure
    ports:
      - "8000:8000"
    environment:
      MONGO_INITDB_ROOT_USERNAME: cocktail
      MONGO_INITDB_ROOT_PASSWORD: cocktail
      MONGO_INITDB_DATABASE: cocktail
    volumes:
      - db:/data/db

volumes:
  db: