version: '3'
services:
  next-app:
    build: ./next-app
    container_name: next-app
    ports:
      - "3000:3000"
    depends_on:
      - api
    image: yutive/next-app
  api:
    build: ./api
    container_name: api
    ports:
      - "8080:8080"
    image: yutive/api